# Generated by Django 4.1 on 2023-11-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='census',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='census',
            name='born_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='census',
            name='civil_state',
            field=models.CharField(choices=[('SI', 'Single'), ('MA', 'Married'), ('DI', 'Divorced'), ('WI', 'Widower')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='census',
            name='gender',
            field=models.CharField(choices=[('MA', 'Male'), ('FE', 'Female'), ('NB', 'Non binary'), ('NP', 'No response')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='census',
            name='works',
            field=models.CharField(choices=[('ST', 'Student'), ('WO', 'Worker'), ('UN', 'Unemployed')], max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('voting_id', 'voter_id', 'born_date', 'gender', 'civil_state', 'works')},
        ),
    ]
