# Generated by Django 4.1 on 2023-12-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_preference_id', models.PositiveIntegerField()),
                ('voter_id', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('voting_preference_id', 'voter_id')},
            },
        ),
    ]
