# Generated by Django 4.1 on 2023-11-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clave',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='isEmailAuthenticated',
            field=models.BooleanField(default=False, help_text='¿Está autenticado su email?'),
        ),
    ]
