# Generated by Django 4.1 on 2023-12-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_clave_user_isemailauthenticated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
